-- Criação do banco de dados
CREATE DATABASE projetointegrador;

-- Usar o banco de dados criado
USE projetointegrador;

-- Criação da tabela ENTIDADES
CREATE TABLE ENTIDADES (
    ID VARCHAR (255)PRIMARY KEY,
    ID_ENTIDADE VARCHAR (255),
    NOME_ENTIDADE VARCHAR (100),
    LOGRADOURO VARCHAR(255),
    CEP VARCHAR(9),
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(50),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(255)
);

-- Criação da tabela PONTOS
CREATE TABLE PONTOS (
    ID VARCHAR (255)PRIMARY KEY,
    ID_ENTIDADE VARCHAR ,
    NOME_ENTIDADE VARCHAR,
    IMG VARCHAR(255),
    DATA_INICIO VARCHAR(20),
    DATA_TERMINO VARCHAR(20),
    DESCRICAO TEXT,
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID)
);

-- Criação da tabela USUARIOADM
CREATE TABLE USUARIOADM (
    ID VARCHAR (255) PRIMARY KEY,
    LOGIN VARCHAR(50),
    SENHA VARCHAR(255)
);